[features]
seeds = false
skip-lint = false

[programs.localnet]
maius_event_manage = "En84b44YzBc3kY1iH8uEo5921nYYuJzUExM54KCx2sku"

[programs.devnet]
maius_event_manage = "En84b44YzBc3kY1iH8uEo5921nYYuJzUExM54KCx2sku"

[programs.mainnet]
maius_event_manage = "En84b44YzBc3kY1iH8uEo5921nYYuJzUExM54KCx2sku"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keypair/keypair.secret.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
