[features]
seeds = false
skip-lint = false

[programs.localnet]
maius_event_manage = "5ZfnmNHBaXSSpNkKa6Eb2dJ4h2psmQ3i8BLR3pJfYbgw"

[programs.devnet]
maius_event_manage = "5ZfnmNHBaXSSpNkKa6Eb2dJ4h2psmQ3i8BLR3pJfYbgw"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keypair/keypair.secret.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
