[features]
seeds = false
skip-lint = false
[programs.devnet]
maius_event_manage = "GniQVVXLwP3FhqBPs15A4cYusnqi12VNFiKGE4rjTcKC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../keypair/keypair.secret.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
