[features]
seeds = false
skip-lint = false
[programs.localnet]
maius_event_manage = "7BuFchofb9XSxdFmQRTdr8px2jywDcDgnBEGoDPXs55n"
[programs.devnet]
maius_event_manage = "7BuFchofb9XSxdFmQRTdr8px2jywDcDgnBEGoDPXs55n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/quanghuy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
