[features]
seeds = false
skip-lint = false

[programs.localnet]
maius_event_manage = "FGjBr55BjGmDrmzu6Sp7BdJBch13zrfWsyDWvdzb7S23"
[programs.devnet]
maius_event_manage = "FGjBr55BjGmDrmzu6Sp7BdJBch13zrfWsyDWvdzb7S23"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/quanghuy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
