# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

before_all do
  Dotenv.overload(".env")
end

TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]

def delete_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_keychain(name, password)
  delete_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  lane :beta do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: APPLE_KEY_ID,
      issuer_id: APPLE_ISSUER_ID,
      key_content: APPLE_KEY_CONTENT,
      duration: 1200,
      in_house: false
    )

    increment_version_number(
      bump_type: "minor"
    )

    increment_build_number(xcodeproj: "MaiusAirdrop.xcodeproj")

    cocoapods(
      clean_install: true
    )

    match(
      type: 'appstore',
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password,
      api_key: api_key
    )

    gym(
      configuration: "Release",
      workspace: "MaiusAirdrop.xcworkspace",
      scheme: "MaiusAirdrop",
      export_method: "app-store",
      output_directory: './build',
      output_name: "MaiusAirdrop.ipa",
    )

    pilot(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: false,
      ipa: "./build/MaiusAirdrop.ipa"
    )

    delete_keychain(keychain_name)

    git_commit(
      path: [
          "./MaiusAirdrop.xcodeproj/project.pbxproj",
          "./MaiusAirdrop/Info.plist",
        ],
       message: "[skip ci] Increment Build number"
     )

    sh("git push origin HEAD:main")

  end
end
