name: Build iOS
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install NPM dependencies
        run: yarn install # if you use npm then please change it to npm

      - name: Test Ruby
        run: ruby -v

      - name: Test Node
        run: node -v

      - name: Test NPM packages
        run: yarn react-native --version

      - name: Install Fastlane
        run: gem install fastlane

      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'beta'
          subdirectory: 'ios'
