name: Build iOS
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: macos-latest
    env:
      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      FASTLANE_USER: 'megatunger@gmail.com'
      FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
      TEMP_KEYCHAIN_PASSWORD: 'login'
      TEMP_KEYCHAIN_USER: 'login'
      APPLE_KEY_ID: '${{ secrets.APPLE_KEY_ID }}'
      APPLE_ISSUER_ID: '${{ secrets.APPLE_ISSUER_ID }}'
      APPLE_KEY_CONTENT: '${{ secrets.APPLE_KEY_CONTENT }}'

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: unnecessary
          key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'
      - run: ssh -T git@github.com || true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install NPM dependencies
        run: yarn install # if you use npm then please change it to npm

      - name: Test Ruby
        run: ruby -v

      - name: Test Node
        run: node -v

      - name: Test NPM packages
        run: yarn react-native --version

      - name: Install Fastlane
        run: bundle install

      - name: Releasing application
        run: cd ios && pod install && fastlane ios beta
